AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 + ECR para API .NET 10 em Docker

Parameters:
  KeyName:
    Type: String
    Description: Key Pair para acesso SSH

Resources:
  ApiRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ec2-api-ecr
      ImageScanningConfiguration:
        ScanOnPush: true

  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref Ec2Role

  ApiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  ApiInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref Ec2InstanceProfile
      SecurityGroupIds:
        - !Ref ApiSecurityGroup
      ImageId: ami-0c02fb55956c7d316 
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user

Outputs:
  RepositoryUri:
    Description: URI do ECR
    Value: !GetAtt ApiRepository.RepositoryUri

  PublicIP:
    Description: IP público da EC2
    Value: !GetAtt ApiInstance.PublicIp

  InstanceId:
    Description: InstanceId da EC2
    Value: !Ref ApiInstance