AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda .NET 10 + HTTP API

Parameters:
  LambdaS3Key:
    Type: String
    Description: S3 key do zip da Lambda

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambda-fn
      Runtime: dotnet10
      Handler: Lambda::Lambda.Function::FunctionHandler
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 256
      Timeout: 10
      Code:
        S3Bucket: !ImportValue LambdaArtifactsBucketName
        S3Key: !Ref LambdaS3Key

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: lambda-http-api
      ProtocolType: HTTP

  ApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt LambdaFunction.Arn
      PayloadFormatVersion: "2.0"

  GetItemsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /items"
      Target: !Sub "integrations/${ApiIntegration}"

  DefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: "$default"
      AutoDeploy: true

  AllowApiInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/*"

Outputs:
  ApiUrl:
    Description: Base URL da HTTP API
    Value: !GetAtt HttpApi.ApiEndpoint
